title: Deployment Models
description: Overview of AI Fabrix deployment options including Azure Marketplace and manual installation
audience:
  - end-user
  - admin
version: stable
owner: product-team
last_reviewed: '2025-09-22'
date: '2025-09-24T15:42:29.845Z'
toc: true
custom_links:
  - text: Getting Started
    url: /aifabrix-docs/docs/getting-started/
    submenu:
      - text: Installation Guide
        url: /aifabrix-docs/docs/getting-started/installation/
      - text: Quick Deploy Guide
        url: /aifabrix-docs/docs/getting-started/quick-deploy/
  - text: Platform Overview
    url: /aifabrix-docs/docs/background/
    submenu:
      - text: Architecture Overview
        url: /aifabrix-docs/docs/background/architecture-overview/
      - text: Competitive Advantages
        url: /aifabrix-docs/docs/background/competitive-advantages/
      - text: Compliance Requirements
        url: /aifabrix-docs/docs/background/compliance-requirements/
      - text: Deployment Models
        url: /aifabrix-docs/docs/background/deployment-models/
      - text: Integration Capabilities
        url: /aifabrix-docs/docs/background/integration-capabilities/
      - text: Modules Overview
        url: /aifabrix-docs/docs/background/modules-overview/
      - text: Platform Overview
        url: /aifabrix-docs/docs/background/platform-overview/
      - text: Target Audience
        url: /aifabrix-docs/docs/background/target-audience/
      - text: Technology Stack
        url: /aifabrix-docs/docs/background/technology-stack/
      - text: Use Cases
        url: /aifabrix-docs/docs/background/use-cases/
  - text: Architecture
    url: /aifabrix-docs/docs/architecture/
    submenu:
      - text: Miso Controller Architecture
        url: /aifabrix-docs/docs/architecture/miso-controller/
      - text: Portal Architecture
        url: /aifabrix-docs/docs/architecture/portal-architecture/
      - text: Security Authentication
        url: /aifabrix-docs/docs/architecture/security-authentication/
  - text: User Guides
    url: /aifabrix-docs/docs/user-guides/
    submenu:
      - text: Portal Usage Guide
        url: /aifabrix-docs/docs/user-guides/portal-usage/
  - text: API Reference
    url: /aifabrix-docs/docs/api/
    submenu:
      - text: AI Fabrix Miso API
        url: /aifabrix-docs/docs/api/miso-api/
seo:
  keywords:
    - AI Fabrix
    - deployment
    - Azure Marketplace
    - installation
    - models
  canonical_url: https://docs.aifabrix.ai/deployment-models
  og_image: images/deployment-models-preview.png
document360:
  category: Background
  visibility: public
  searchable: true
  featured: true
  order: 7
layout: doc
